name: CI-CD

on:
  push:
    branches: [master]

jobs:


  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        context: [app, database, payment_gateway, reverse_proxy]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image ${{ matrix.context }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.context }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.context }}_fp:latest, ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.context }}_fp:${{ github.sha }}