name: CI

on:

  pull_request:
    branches: [ master ]


jobs:

  set-up:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 11

        
  build:

    needs: set-up
    
    runs-on: ubuntu-latest
    
    steps:    
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn -B package --file app/pom.xml


  test:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test with Maven
      run: mvn -B test --file app/pom.xml